### PR TITLE
deleted textfile

### PR DESCRIPTION
**Pull request by AmnahRazzaki**
This change is [Reviewable](https://reviewable.io/reviews/amnahrazzaki/car_game/5)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/AmnahRazzaki/Car_game/pull/5" target="_blank">ReviewNinja

**Comment by AmnahRazzaki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[text.txt, line 0 \[r1\]](https://reviewable.io:443/reviews/amnahrazzaki/car_game/5#-KMuuHqv2BhlFvBo4t21:-KMuuHqwaO8RQH4FFdQV:676635175) ([raw file](https://github.com/amnahrazzaki/car_game/blob/b3ff1082d76696cb95727ea7417a190ea9e3bf7d/text.txt#L0)):*
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amnahrazzaki/car_game/5)*

**Comment by AmnahRazzaki** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/amnahrazzaki/car_game/5)*

**Comment by AmnahRazzaki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[text.txt, line  \[r1\]](https://reviewable.io:443/reviews/amnahrazzaki/car_game/5#-KMuuHqv2BhlFvBo4t21:-KMuvkNL_4YpVa9Ml3vB:676958649) ([raw file](https://github.com/amnahrazzaki/car_game/blob/b3ff1082d76696cb95727ea7417a190ea9e3bf7d/text.txt#L)):*
<details><summary><i>Previously, AmnahRazzaki wrote…</i></summary>
> Done
</details>
Okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/amnahrazzaki/car_game/5)*

**Pull request merged**
